
#' Power Generated by Automobiles
#'
#'This function determines the power required to keep a car moving at a given speed.
#' @param V is vehicle speed (assuming no headwind) in m/s (or mps)
#' @param m is vehicle mass in kg
#' @param A is surface area of car (m2)
#' @param g is acceleration due to gravity (9.8m/s2)
#' @param p_air = density of air (1.2kg/m3)
#' @param crolling is a rolling and aerodynamic resistive coefficient, typical value is 0.015.
#' @param cdrag ia a rolling and aerodynamic resistive coefficient, typical value is 0.3.
#' @return Pb which is power in Watts
#'
# function definition
power_gen_orig = function(V,A,m,g=9.8,p_air=1.2,crolling=0.015,cdrag=0.3) {
  Pb = crolling*m*g*V + (1/2)*A* p_air *cdrag* V^3
  return(Pb)
}
